### ISSUE TITLE
X11 window errors

### ISSUE THREAD

**Issue by pgruenbacher** [BearishSun/BansheeEngine#301]
LinuxWindow::setIcon is producing an X11 invalid window error. I haven't isolated yet but commenting out the function resolves the error message: 
```
[WARNING] X11 error: BadWindow (invalid Window parameter)
		 in int bs::x11ErrorHandler(Display*, XErrorEvent*) [/home/pgruenbacher/build/bsframework/BansheeEngine/Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:254]

```

I'm also getting a separate stacktrace 
```
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) bs.Editor.ModalWindow.Internal_CreateInstance (bs.Editor.ModalWindow,bool) [0x00000] in <1551f472a943452ab236385e5ef2aab0>:0
  at bs.Editor.ModalWindow..ctor (bool) [0x00006] in <1551f472a943452ab236385e5ef2aab0>:0
  at bs.Editor.ProjectWindow..ctor () [0x00000] in <1551f472a943452ab236385e5ef2aab0>:0
  at bs.Editor.ProjectWindow.Open () [0x00000] in <1551f472a943452ab236385e5ef2aab0>:0
  at bs.Editor.Program.OnEditorStartUp () [0x00023] in <1551f472a943452ab236385e5ef2aab0>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0001e] in <7609ea8370644d7fbd7633f24ac33b3e>:0
```

which i isolated to here, which i could resolve by confirming that linuxWindow != nullptr after getCustomAttribute

```
	void Platform::setCaptionNonClientAreas(const ct::RenderWindow& window, const Vector<Rect2I>& nonClientAreas)
	{
		if(nonClientAreas.size() == 0)
			return;

		Lock lock(mData->lock);

		LinuxWindow* linuxWindow{nullptr};
		window.getCustomAttribute("LINUX_WINDOW", &linuxWindow);


		if (!linuxWindow) return;
		linuxWindow->_setDragZones(nonClientAreas);
	}
```

But even after resolving these, I get some more X11 errors...
Why not just use SDL for window and render target? There's a lot of code in here regarding the platform windows and such...

**Comment by BearishSun** [comment]
Hi, thanks, I'll take a look when I can. Currently the Linux version is untested and unsupported. I should hopefully be doing a pass on it later next month.

**Comment by nsneck** [comment]
For what it's worth, one setIcon crash appears to happen due to the XCreatePixmap() call in LinuxPlatform::createPixmap (which is called by LinuxWindow::setIcon() for setting the icon "the old way".
Found this by forcing all X calls to be synchronous via XSynchronize(display, True); and checking the backtrace upon hitting x11ErrorHandler in gdb.

```
Thread 1 "Banshee3D" hit Breakpoint 1, bs::x11ErrorHandler (display=0xe3e5d0, event=0x7fffffffd690) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
249		{
(gdb) backtrace
#0  0x00007ffff64e530e in bs::x11ErrorHandler(_XDisplay*, XErrorEvent*) (display=0xe3e5d0, event=0x7fffffffd690) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
#1  0x00007ffff2ee38fa in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff2ee082b in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff2ee08d5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff2ee1830 in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff2edd1cd in XSync () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff2edd26b in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff2ee420f in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff2ebfcb0 in XCreatePixmap () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007ffff64e9631 in bs::LinuxPlatform::createPixmap(bs::PixelData const&, unsigned int) (data=..., depth=24) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:1483
#10 0x00007ffff64f14b5 in bs::LinuxWindow::setIcon(bs::PixelData const&) (this=0x7fffdc007570, data=...) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxWindow.cpp:388
#11 0x00007ffff64e612c in bs::Platform::setIcon(bs::PixelData const&) (pixelData=...) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:414
#12 0x00007ffff6b34c25 in bs::Application::onStartUp() (this=0xe3e070) at ../Source/bsf/Source/Foundation/bsfEngine/BsApplication.cpp:67
#13 0x00007ffff797005c in bs::EditorApplication::onStartUp() (this=0xe3e070) at ../Source/EditorCore/BsEditorApplication.cpp:87
#14 0x00007ffff7974b45 in bs::Module<bs::CoreApplication>::startUp<bs::EditorApplication>() () at ../Source/bsf/Source/Foundation/bsfUtility/Utility/BsModule.h:92
#15 0x00007ffff79702f1 in bs::EditorApplication::startUp() () at ../Source/EditorCore/BsEditorApplication.cpp:148
#16 0x0000000000970a05 in main() () at ../Source/Banshee3D/BsEditorExec.cpp:49
```
I tried to make some sense of why it's causing the X error but couldn't. Here's the PixelData and depth involved:

```
Thread 1 "Banshee3D" hit Breakpoint 2, bs::LinuxPlatform::createPixmap (data=..., depth=24) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:1465
1465		{
(gdb) info args
data = @0x7fffffffda90: {<bs::GpuResourceData> = {<bs::IReflectable> = {_vptr.IReflectable = 0x7ffff72d27b0 <vtable for bs::PixelData+16>}, mData = 0x8fd7580 "\234\234\234", mOwnsData = true, mLocked = false}, 
  mExtents = {left = 0, top = 0, right = 128, bottom = 128, front = 0, back = 1}, mFormat = bs::PF_RGBA8, mRowPitch = 512, mSlicePitch = 65536}
depth = 24
```

However, if I just comment out "the old way" of setting the icon, I get a new x11 error, in LinuxWindow::setIcon(), with the line
`Atom iconAtom = XInternAtom(display, "_NET_WM_ICON", False);`

Backtrace:
```
Thread 1 "Banshee3D" hit Breakpoint 1, bs::x11ErrorHandler (display=0xe3e5d0, event=0x7fffffffd800) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
249		{
(gdb) backtrace
#0  0x00007ffff64e621e in bs::x11ErrorHandler(_XDisplay*, XErrorEvent*) (display=0xe3e5d0, event=0x7fffffffd800) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
#1  0x00007ffff2ee48fa in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff2ee182b in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff2ee18d5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff2ee2830 in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff2ecd11f in XInternAtom () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff64f24aa in bs::LinuxWindow::setIcon(bs::PixelData const&) (this=0x7fffdc007570, data=...) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxWindow.cpp:409
#7  0x00007ffff64e703c in bs::Platform::setIcon(bs::PixelData const&) (pixelData=...) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:414
#8  0x00007ffff6b35a81 in bs::Application::onStartUp() (this=0xe3e070) at ../Source/bsf/Source/Foundation/bsfEngine/BsApplication.cpp:67
#9  0x00007ffff797005c in bs::EditorApplication::onStartUp() (this=0xe3e070) at ../Source/EditorCore/BsEditorApplication.cpp:87
#10 0x00007ffff7974b45 in bs::Module<bs::CoreApplication>::startUp<bs::EditorApplication>() () at ../Source/bsf/Source/Foundation/bsfUtility/Utility/BsModule.h:92
#11 0x00007ffff79702f1 in bs::EditorApplication::startUp() () at ../Source/EditorCore/BsEditorApplication.cpp:148
#12 0x0000000000970a05 in main() () at ../Source/Banshee3D/BsEditorExec.cpp:49
```

However, if we go even further and just comment out the whole setIcon function, we get this awesome error in bs::applyCurrentCursor calling XUndefineCursor():

```
Thread 3 "Banshee3D" hit Breakpoint 1, bs::x11ErrorHandler (display=0xe3e5d0, event=0x7fffea160fe0) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
249		{
(gdb) backtrace
#0  0x00007ffff64e60ee in bs::x11ErrorHandler(_XDisplay*, XErrorEvent*) (display=0xe3e5d0, event=0x7fffea160fe0) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:249
#1  0x00007ffff2ee58fa in _XError () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#2  0x00007ffff2ee282b in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#3  0x00007ffff2ee28d5 in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff2ee3830 in _XReply () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff2edf1cd in XSync () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff2edf26b in  () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff2ee0aaa in XUndefineCursor () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff64e5bca in bs::applyCurrentCursor(bs::Platform::Pimpl*, unsigned long) (data=0xe03920, window=140737324882797) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:143
#9  0x00007ffff64ea064 in bs::LinuxPlatform::_registerWindow(unsigned long, bs::LinuxWindow*) (xWindow=140737324882797, window=0x7fffdc404e00)
    at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxPlatform.cpp:1446
#10 0x00007ffff64f1b43 in bs::LinuxWindow::LinuxWindow(bs::WINDOW_DESC const&) (this=0x7fffdc404e00, desc=...) at ../Source/bsf/Source/Foundation/bsfCore/Private/Linux/BsLinuxWindow.cpp:245
#11 0x00007ffff79ceaed in bs::bs_new<bs::LinuxWindow, bs::WINDOW_DESC&>(bs::WINDOW_DESC&) (args#0=...) at ../Source/bsf/Source/Foundation/bsfUtility/Allocators/BsMemoryAllocator.h:354
#12 0x00007ffff79ce68a in bs::SplashScreen::create() () at ../Source/EditorCore/Utility/BsSplashScreen.cpp:131
#13 0x00000000005bc808 in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#14 0x000000000082295e in std::function<void ()>::operator()() const (this=0x7fffdc000c90) at /usr/include/c++/7/bits/std_function.h:706
#15 0x00007ffff63fb384 in bs::CommandQueueBase::playbackWithNotify(std::queue<bs::QueuedCommand, std::deque<bs::QueuedCommand, bs::StdAlloc<bs::QueuedCommand, bs::GenAlloc> > >*, std::function<void (unsigned int)>) (this=0xe63530, commands=0x7fffdc000b60, notifyCallback=...) at ../Source/bsf/Source/Foundation/bsfCore/CoreThread/BsCommandQueue.cpp:126
#16 0x00007ffff6418bc7 in bs::CoreThread::runCoreThread() (this=0xe63370) at ../Source/bsf/Source/Foundation/bsfCore/CoreThread/BsCoreThread.cpp:140
#17 0x00007ffff641ea21 in std::__invoke_impl<void, void (bs::CoreThread::*&)(), bs::CoreThread*&>(std::__invoke_memfun_deref, void (bs::CoreThread::*&)(), bs::CoreThread*&) (__f=@0x7fffdc000b40: (void (bs::CoreThread::*)(bs::CoreThread * const)) 0x7ffff6418a02 <bs::CoreThread::runCoreThread()>, __t=@0x7fffdc000b50: 0xe63370) at /usr/include/c++/7/bits/invoke.h:73
#18 0x00007ffff641e21a in std::__invoke<void (bs::CoreThread::*&)(), bs::CoreThread*&>(void (bs::CoreThread::*&)(), bs::CoreThread*&) (__fn=@0x7fffdc000b40: (void (bs::CoreThread::*)(bs::CoreThread * const)) 0x7ffff6418a02 <bs::CoreThread::runCoreThread()>, __args#0=@0x7fffdc000b50: 0xe63370) at /usr/include/c++/7/bits/invoke.h:95
#19 0x00007ffff641d9f5 in std::_Bind<void (bs::CoreThread::*(bs::CoreThread*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0x7fffdc000b40, __args=...)
    at /usr/include/c++/7/functional:467
#20 0x00007ffff641cf53 in std::_Bind<void (bs::CoreThread::*(bs::CoreThread*))()>::operator()<, void>() (this=0x7fffdc000b40) at /usr/include/c++/7/functional:551
#21 0x00007ffff641c085 in std::_Function_handler<void (), std::_Bind<void (bs::CoreThread::*(bs::CoreThread*))()> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/7/bits/std_function.h:316
#22 0x000000000082295e in std::function<void ()>::operator()() const (this=0x7fffea1618f0) at /usr/include/c++/7/bits/std_function.h:706
#23 0x00007ffff634e929 in bs::PooledThread::run() (this=0xe63b30) at ../Source/bsf/Source/Foundation/bsfUtility/Threading/BsThreadPool.cpp:115
#24 0x00007ffff6351f9d in std::__invoke_impl<void, void (bs::PooledThread::*&)(), bs::PooledThread*&>(std::__invoke_memfun_deref, void (bs::PooledThread::*&)(), bs::PooledThread*&) (__f=@0xe63c58: (void (bs::PooledThread::*)(bs::PooledThread * const)) 0x7ffff634e7ee <bs::PooledThread::run()>, __t=@0xe63c68: 0xe63b30) at /usr/include/c++/7/bits/invoke.h:73
#25 0x00007ffff6351d6a in std::__invoke<void (bs::PooledThread::*&)(), bs::PooledThread*&>(void (bs::PooledThread::*&)(), bs::PooledThread*&) (__fn=@0xe63c58: (void (bs::PooledThread::*)(bs::PooledThread * const)) 0x7ffff634e7ee <bs::PooledThread::run()>, __args#0=@0xe63c68: 0xe63b30) at /usr/include/c++/7/bits/invoke.h:95
#26 0x00007ffff6351995 in std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (this=0xe63c58, __args=...)
    at /usr/include/c++/7/functional:467
#27 0x00007ffff6351463 in std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>::operator()<, void>() (this=0xe63c58) at /usr/include/c++/7/functional:551
#28 0x00007ffff6350ba3 in std::__invoke_impl<void, std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>>(std::__invoke_other, std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>&&) (__f=...)
    at /usr/include/c++/7/bits/invoke.h:60
#29 0x00007ffff6350337 in std::__invoke<std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>>(std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()>&&) (__fn=...)
    at /usr/include/c++/7/bits/invoke.h:95
#30 0x00007ffff6352290 in std::thread::_Invoker<std::tuple<std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()> > >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0xe63c58)
    at /usr/include/c++/7/thread:234
#31 0x00007ffff635224c in std::thread::_Invoker<std::tuple<std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()> > >::operator()() (this=0xe63c58) at /usr/include/c++/7/thread:243
#32 0x00007ffff6352204 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::_Bind<void (bs::PooledThread::*(bs::PooledThread*))()> > > >::_M_run() (this=0xe63c50) at /usr/include/c++/7/thread:186
#33 0x00007ffff489c66f in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#34 0x00007ffff225d6db in start_thread (arg=0x7fffea162700) at pthread_create.c:463
#35 0x00007ffff417188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Commenting out XUndefineCursor() isn't enough, as then it'll error in the same function calling XDefineCursor(). The good news are that these 5 errors are the last x11 errors you get when trying to launch the editor. The bad news are that you can't actually do anything with the editor, clicks don't appear to be registering, you can't open any menus etc. apart from the Project Manager window, where you can write to the Project path field and click the "Automatically load last open project" checkbox.
